#!/usr/bin/env bash

# Script to check the existence and type of the "school" file

FILE="school"

if [ -e "$FILE" ]; then
    if [ -f "$FILE" ]; then
        if [ -s "$FILE" ]; then
            echo "File exists and is a regular file"
        else
            echo "School exists but empty"
        fi
    elif [ -d "$FILE" ]; then
        echo "School exists but it's a directory"
    fi
else
    echo "School doesn’t exist"
fi
